### ISSUE TITLE
Error when i ask LLM via UTF-8 chars

### ISSUE THREAD

**Issue by belariflouiza** [evgenyigumnov/rustsn#24]
I tried to generate using cargo run -- --lang=PYTHON but i had this error !
**there is example**  
![image](https://github.com/user-attachments/assets/7f5c5470-eda4-4fc4-a951-b2697821c187)
and  i got this :
![image](https://github.com/user-attachments/assets/67a99892-5e7b-4d1a-a167-157e79372310)

**Comment by evgenyigumnov** [comment]
Cant reproduce :(

**Comment by evgenyigumnov** [comment]
https://github.com/evgenyigumnov/rustsn/commit/60feb7af3410d630f63e0c56bc4eb1a4e0fe18a9

**Comment by belariflouiza** [comment]
removing stop word, resoled it
