### ISSUE TITLE
Ollama "qwen2.5-coder:1.5b" model support (parse problems in "parse_llm_response" functions)

### ISSUE THREAD

**Issue by evgenyigumnov** [evgenyigumnov/rustsn#27]
if you set "qwen2.5-coder:1.5b" in llm_api.rs then all "parse_llm_response" functions do not parse qwen2.5-coder reply to create Project struct.

Its some times create empty for example

```
Project {
    cargo_toml: "",
    lib_rs: "",
    build: "",
    test: "",
}
```

**Comment by evgenyigumnov** [comment]
parse_llm_response refactoring need. A lot of copy-past code. Many-to-one "parse_llm_response" function refactoring required. Replace multiple parse_llm_response function to one. With additional paramater Lang and common Project struct


```
#[derive(Debug)]
pub struct Project {
    pub project_build_script: String,
    pub additional_config: Optiona<String>,
    pub solution_code: String,
    pub test_code: String,
    pub install_dependecy_command: Optional<String>,
    pub build_command: String,
    pub test_command: String,
}

```

**Comment by Longlom** [comment]
Took
